name: ✨ Feature Request
description: Suggest a new feature or enhancement for the gofast library
title: "[FEATURE] <brief description>"
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for **gofast**! Please fill out the form below to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or changed?
      placeholder: "Describe the feature you're requesting."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you need this feature? What problem does it solve?
      placeholder: "Explain the context or problem you're trying to solve."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you imagine this working in gofast?
      placeholder: "Describe how this feature might be implemented or used."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you tried alternative approaches?
      placeholder: "Describe any workarounds or existing features you’ve tried."

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have considered the scope and impact of this feature
          required: true
